{% set name = "algotree" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d509374d77ca22a5ad6f0f6763cf70792c127fb091029b50a2f96885cbe0fb2f

build:
  entry_points:
    - algotree=AlgoTree.shell.cli:main
    - algotree-shell=AlgoTree.shell.shell:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - prompt_toolkit >=3.0.0

test:
  imports:
    - AlgoTree
  commands:
    - pip check
    - algotree --help
    - algotree-shell --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/queelius/AlgoTree
  doc_url: https://queelius.github.io/AlgoTree/
  summary: A algorithmic tookit for working with trees in Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
